### ISSUE TITLE
"No contents in first page" error when signing PDF with "Visible" parameters

### ISSUE THREAD

**Issue by despotovski01** [WindowsNT/AdES#2]
Hello.
First of all, thank you for this useful library. I'm having trouble signing a PDF file with visible parameters. I get the error "No contents in first page". The PDF I'm trying to sign is the following: https://cs.stanford.edu/~jure/pubs/node2vec-kdd16.pdf
The "Visible" signing parameters in use are the following (actually, I've tried many combinations, even the default ones, with no avail, so they might not be relevant):
```
Params.pdfparams.Visible.top = 10;
Params.pdfparams.Visible.left = 10;
Params.pdfparams.Visible.wi = 10;
Params.pdfparams.Visible.fs = 10;
Params.pdfparams.Visible.t = "test";
```
This is the first PDF I've had this error with so far. It works on other files.
Can you please help me with this problem?
Regards,
Aleksandar

**Comment by WindowsNT** [comment]
Thx for your suggestion.
